### ISSUE TITLE
CJ1117-3.3 not availabe

### ISSUE THREAD

**Issue by ProstetnikJeltz** [feilipu/yaz180#6]
Hello,

the LDO CJ1117-3.3 is not available (even not at digikey), when trying to order from Germany - there are some retailers in China (but not at Aliexpress).
I searched all my sources but weren't able to get this LDO (Digikey, Mouser, RS-Components, Ebay, Aliexpress, Banggood ... ).
The problem is, that it is SOT-89-3 and not SOT-223, which is easy to find.
There are also no cross references available, because all other LDOs have Vin and Vout vice versa.
My solution by now is, to mount an SOT-223 AMS1117-3.3 in vertical position and hope, it won't get too hot, because the "heat spreader" is not soldered to the PCB.

Second problem is, that the footprints for the Diodes D2 and D4 (SOD-idontknow) differ from D1 and D3 (SOD-323).
So D2 and D4 don't fit to the PCB - I "wire wrapped" them, but this is a quite dirty solution for switching diodes ;) .

The PCB used, is the latest in folder "V24_20190107".

This is not a cpomplaint but a suggestion for further planning.
I really appreciate you work and look forward, when my YAZ180 sees the "first light".

Greetings from Munich
Uli

**Comment by feilipu** [comment]
>  mount an SOT-223 AMS1117-3.3 in vertical position and hope, it won't get too hot.
You'll be fine. There is only the I2C chips and the ESP8266 on the 3V line.

It is unfortunate that I used that layout. It was only because I had a bunch of them handy from a prior project, and wanted to reuse them.

> Diodes D2 and D4 (SOD-idontknow) differ from D1 and D3 (SOD-323).

Yes. this is still an issue. I try to use "bigger" 2A diodes for the 5V circuit, and they don't quite fit on the pads correctly. I couldn't find an Eagle diode of appropriate size, so the diodes hang over the silkscreen slightly. That makes them hard to solder, unless you use paste.

I've not revised the PCB from the latest 2019 one, which you have. Been distracted by some software projects for the past months. I've been thinking about another version, but anything else I can think of right now would look a lot like the SC131 (and that's been done). [Here's some blinking lights for inspiration](https://youtu.be/CFe9-Dl6wxA).

Good luck with your build, Uli.

**Comment by ProstetnikJeltz** [comment]
Hello Philip,

thank you for your reply.

I‘ll try to mount the two diodes vertically and use a short wire for connecting to kathode/ground.
I just thought, fi you plan to relesa another PCB … 😉 .

The AMS1117 should do it, if not, I’ll solder a small piece of copper to the heatspreader.
Just waiting for the debouncer and the switching regulator, the it will run ( I hope so).
I also have several SC126 running, but the YAZ is quite more sophisticated 😊 .

To find smaller diodes for 2A is very hard, I tried to after I discovered the mounting problems.
But I keep on searching and if I find one that fits, I‘ll tell you.

I’m working at BMW as Testengineer and we have some very useful collections of SMDs, maybe searching there gets a hit 😉 .

Greetings form Munich and stay healthy

Uli
